version: '3.9'

services:
  go-mux-repositories-pattern:
    container_name: go-mux-repositories-pattern
    image: bossnanda/go-mux-repositories-pattern:1.0.0
    build: .
    environment:
      DATABASE_HOST: "go-mux-repositories-pattern-db"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_SSLMODE: "disable"
      DATABASE_URL: "host=go-mux-repositories-pattern-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8001:8001"
    depends_on:
      - go-mux-repositories-pattern-db
  go-mux-repositories-pattern-db:
    container_name: go-mux-repositories-pattern-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
